# This workflow will build 

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    name: Test & Build
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Run tests
        run: mvn -B test
      
      - name: Build local jar
        run:  mvn package -Dmaven.test.skip=true
        
      - name: Build hadoop jar
        run:  mvn package -Dmaven.test.skip=true -P hadoop
        
      - name: Prepare artifacts
        run: |
          mkdir -p artifacts 
          cp target/flink-aggregations-*-*.jar artifacts
          echo -e "ref: $GITHUB_REF \ncommit: $GITHUB_SHA\nbuild: $(date +"%Y-%m-%dT%H:%M:%SZ")" > artifacts/info.txt
        
      - name: Upload artifacts
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: artifacts/*.*

      - name: Update nightly release
        uses: eine/tip@master
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: artifacts/*.*
